"""initial schema

Revision ID: b1ced42d0ca2
Revises: 
Create Date: 2026-09-27 06:12:52.327042
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

revision: str = 'b1ced42d0ca2'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('article',
    sa.Column('article_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('article_date', sa.Date(), nullable=False),
    sa.Column('section_code', sa.String(length=10), nullable=False),
    sa.Column('detail_section_code', sa.String(length=10), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('content', sa.Text().with_variant(mysql.MEDIUMTEXT(), 'mysql'), nullable=False),
    sa.Column('url', sa.String(length=255), nullable=False),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('article_id'),
    sa.UniqueConstraint('url')
    )
    op.create_index(op.f('ix_article_article_date'), 'article', ['article_date'], unique=False)
    op.create_table('daily_keyword',
    sa.Column('daily_keyword_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('keyword_date', sa.Date(), nullable=False),
    sa.Column('word', sa.String(length=100), nullable=False),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('daily_keyword_id'),
    sa.UniqueConstraint('keyword_date', 'word')
    )
    op.create_index(op.f('ix_daily_keyword_keyword_date'), 'daily_keyword', ['keyword_date'], unique=False)
    op.create_table('google_keyword',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_google_keyword_id'), 'google_keyword', ['id'], unique=False)
    op.create_table('realtime_keyword',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_realtime_keyword_id'), 'realtime_keyword', ['id'], unique=False)
    op.create_table('topic_trend',
    sa.Column('topic_trend_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('trend_date', sa.Date(), nullable=False),
    sa.Column('topic', sa.String(length=100), nullable=False),
    sa.Column('frequency', sa.Integer(), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('topic_trend_id'),
    sa.UniqueConstraint('trend_date', 'topic')
    )
    op.create_index(op.f('ix_topic_trend_trend_date'), 'topic_trend', ['trend_date'], unique=False)
    op.create_table('user',
    sa.Column('user_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_name', sa.String(length=50), nullable=False),
    sa.Column('user_password', sa.String(length=100), nullable=False),
    sa.Column('user_email', sa.String(length=50), nullable=False),
    sa.Column('user_status', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_connected_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('user_name')
    )
    op.create_index(op.f('ix_user_user_email'), 'user', ['user_email'], unique=True)
    op.create_table('post',
    sa.Column('post_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=50), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('post_date', sa.DateTime(), nullable=False),
    sa.Column('writer_email', sa.String(length=50), nullable=False),
    sa.Column('writer_name', sa.String(length=50), nullable=False),
    sa.Column('tag', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['writer_email'], ['user.user_email'], ),
    sa.PrimaryKeyConstraint('post_id')
    )
    op.create_index(op.f('ix_post_post_id'), 'post', ['post_id'], unique=False)
    op.create_index(op.f('ix_post_title'), 'post', ['title'], unique=False)
    op.create_table('comment',
    sa.Column('comment_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('comment_date', sa.DateTime(), nullable=False),
    sa.Column('writer_email', sa.String(length=50), nullable=False),
    sa.Column('writer_name', sa.String(length=50), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['post.post_id'], ),
    sa.ForeignKeyConstraint(['writer_email'], ['user.user_email'], ),
    sa.PrimaryKeyConstraint('comment_id')
    )
    op.create_index(op.f('ix_comment_comment_id'), 'comment', ['comment_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_comment_comment_id'), table_name='comment')
    op.drop_table('comment')
    op.drop_index(op.f('ix_post_title'), table_name='post')
    op.drop_index(op.f('ix_post_post_id'), table_name='post')
    op.drop_table('post')
    op.drop_index(op.f('ix_user_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_topic_trend_trend_date'), table_name='topic_trend')
    op.drop_table('topic_trend')
    op.drop_index(op.f('ix_realtime_keyword_id'), table_name='realtime_keyword')
    op.drop_table('realtime_keyword')
    op.drop_index(op.f('ix_google_keyword_id'), table_name='google_keyword')
    op.drop_table('google_keyword')
    op.drop_index(op.f('ix_daily_keyword_keyword_date'), table_name='daily_keyword')
    op.drop_table('daily_keyword')
    op.drop_index(op.f('ix_article_article_date'), table_name='article')
    op.drop_table('article')
    # ### end Alembic commands ###
